[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "cd backend && python3.11 -m pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
